controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
  
login_check:
    path: /api/login_check
    controller: App\Controller\Security\LoginController::login

